name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *' # At 00:00 on the first day of every month'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Docker/ENV cleanup Cleanup
      run: |
        docker image prune -a -f
        docker container prune -f
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        tags: ghcr.io/kastnerrg/qualcomm-docker-image:latest
        platforms: linux/aarch64
        push: true
